### ISSUE TITLE
Incorrect behavior when a subgroup is requested by a user who is subsequently removed from the enclosing group

### ISSUE THREAD

**Issue by jarofmy** [maniaclab/ci-connect-api#2]
Edgecase 1:
- User A is 'active' member of Group 1,
- User A requests to create sub-project in Group 1.
- User A is removed from Group 1 before request for sub-project is approved or denied (still pending)

Edgecase 2:
- User A is 'active' member of Group 1,
- User A requests to create sub-project in Group 1.
- Request for sub-project is approved
- User A is removed from Group 1
- Currently: User A still remains as admin member of sub-project

**Comment by cnweaver** [comment]
Case 2 moved to #2
